### PR TITLE
try this

### PR DESCRIPTION
**Pull request by kingsotn**

### CODE REVIEW

**Comment by andrebhu** [comment]
lgtm?

**Comment by sergey-hovhannisyan** [comment]
The pipeline accepts a model object, not a string. But lmk if you figure out how to return a list of all available SA models 👍🏻

**Comment by kingsotn** [comment]
> The pipeline accepts a model object, not a string. But lmk if you figure out how to return a list of all available SA models 👍🏻 

You can lookup model names on hugging face and paste them in model list and it should work

**Comment by sergey-hovhannisyan** [comment]
Right, that's my default solution,  but I wanted to fetch all available models from within the transformers package.

**Pull request closed without merging**
